apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090/prometheus
    isDefault: true
    jsonData:
      httpMethod: GET
      timeField: time
    editable: true
