DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;

FLUSH PRIVILEGES;
CREATE USER IF NOT EXISTS 'test'@'localhost' IDENTIFIED BY 'test';
GRANT ALL PRIVILEGES ON *.* TO 'test'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
